#!/bin/sh

SSH_ASKPASS=ssh-askpass

gnome-settings-daemon
gnome-power-manager &
xscreensaver -no-splash &
gs-xs-proxy &

syndaemon -d -t -i 1
synclient TapButton1=1
synclient TapButton2=3
synclient TapButton3=2
synclient FastTaps=1
synclient MinSpeed=0.1
synclient MaxSpeed=0.5
synclient AccelFactor=0.015
xinput set-prop appletouch "Device Accel Constant Deceleration" 1.0
xinput set-prop appletouch "Device Accel Adaptive Deceleration" 10.0
xset m 3 30

nm-applet &
# wicd-gtk > /dev/null &

xsetroot -solid black
wmname LG3D

exec ssh-agent awesome
