#!/bin/bash

export LANG="en_US"

ADRAKE_MODULES="XHax AdobeReader"
. /afs/adrake.org/sourceme.bash

xrdb $HOME/.Xresources
xsetroot -solid black &

if [ -f ~/.Xmodmap ]; then
	xmodmap ~/.Xmodmap
fi

xset b off

killall scim-launcher
exec awesome
exec gnome-session
